### ISSUE TITLE
Set up Env variables for Emails

### ISSUE THREAD

**Issue by Tanuj22** [anshulahuja98/spc_portal#73]
**Describe the bug**
Currently, automated emails are sent to students and recruiters when they register. We want to set up env variables so that we can stop this feature if needed in production by just changing the env variables.

**Expected behavior**
Set up env variables in [.env.example](https://github.com/anshulahuja98/spc_portal/blob/master/.env.example) file. There should a check before every email.

**Comment by MohanChhabaria** [comment]
@Tanuj22 i will give it a try.
