### ISSUE TITLE
Username field should mention that it is supposed to roll no

### ISSUE THREAD

**Issue by Tanuj22** [anshulahuja98/spc_portal#74]
**Describe the bug**
The [student registration page](https://spc.iitj.ac.in/student/register/) username field is supposed to be the roll no of students. It doesn't mention it currently.

**Comment by DarshitJain04** [comment]
@Tanuj22 
I'll work on this

**Comment by Tanuj22** [comment]
@DarshitJain04 Take one issue at a time. Make sure  you have some dummy Gmail id setup in the `.env` file as if you login it will throw an error without it.
