### ISSUE TITLE
Change SPC to CDC in Emails

### ISSUE THREAD

**Issue by Tanuj22** [anshulahuja98/spc_portal#75]
**Describe the bug**
The email sent to students and recruiters mentions `SPC` and `Office of Student Placement`. It should be changed to `CDC` and `Career Development Cell` respectively.
![Screenshot from 2020-06-16 23-26-04](https://user-images.githubusercontent.com/42486853/84810894-9fd67080-b029-11ea-8430-5227d5a7ae8d.png)

**Comment by Sahil1479** [comment]
I'll work on this

**Comment by Tanuj22** [comment]
Check my comment on #74
