### ISSUE TITLE
CDC logo should redirect to home page when clicked

### ISSUE THREAD

**Issue by Tanuj22** [anshulahuja98/spc_portal#77]
**Describe the bug**
The `CDC logo` on the [students details](https://spc.iitj.ac.in/student/details/) to take you to the home screen when clicked upon.

P.S. _You need to be logged in to visit that page._

**Comment by MohanChhabaria** [comment]
@Tanuj22 i will work on this

**Comment by Tanuj22** [comment]
Check my comment on #74
