### ISSUE TITLE
Navbar not styled properly in phone view

### ISSUE THREAD

**Issue by anmolcool007** [anshulahuja98/spc_portal#78]
**Describe the bug**
There's a vertical gap in the heading due to the drop-down hamburger button as they don't fit together on the screen.

**To Reproduce**
1. Switch to phone view
2. See error

**Expected behavior**
There should be proper padding and margin in image heading and hamburger menu when switched to the phone view.

**Screenshots**
![responsiveness](https://user-images.githubusercontent.com/43794036/84813721-fd6cbc00-b02d-11ea-9fbc-265e3760d433.png)

**Comment by anmolcool007** [comment]
I would suggest changing padding/margin of image and heading and also font size of heading below a particular screen size via css.

**Comment by Kartik-3004** [comment]
@anmolcool007 I will work on this

**Comment by Kartik-3004** [comment]
@Tanuj22 I will work on this
