### ISSUE TITLE
Overflow of Drop down box in X axis

### ISSUE THREAD

**Issue by anmolcool007** [anshulahuja98/spc_portal#79]
**Describe the bug**
The dropdown of CDC team and Login tab overflows in X-axis. 
On the homepage, the overflow is not allowed so a part of the drop-down box gets cut out of the window.
While on other pages there is a tendency to scroll horizontally

**Expected behavior**
There should be no horizontal scroll and the drop-down box should be completely visible on the screen.

**Screenshots**
Homepage
![Screenshot from 2020-06-17 01-14-54](https://user-images.githubusercontent.com/43794036/84821669-1af35300-b039-11ea-929a-0ad0d0d3e736.png)
Other pages
![Screenshot from 2020-06-17 01-15-51](https://user-images.githubusercontent.com/43794036/84821706-28104200-b039-11ea-8182-70a4f97d9282.png)

**Comment by Sahil1479** [comment]
@Tanuj22 i will try to solve this bug.

**Comment by Kartik-3004** [comment]
@Tanuj22 I will work on this . And on which branch to put a PR ?

**Comment by Tanuj22** [comment]
I meant that donot send a PR from the master of you forked repo. Create a new branch for each PR you work on and send a PR from it.

**Comment by MohanChhabaria** [comment]
@Tanuj22  I have made some change in css of the dropdown menu.  I am attaching the screenshot. Let me know if this is OK.
![ss1](https://user-images.githubusercontent.com/63086398/88460944-8d1f4900-cebd-11ea-9b25-15777ba9f64b.jpg)
![ss2](https://user-images.githubusercontent.com/63086398/88460946-8f81a300-cebd-11ea-9590-d37ff33cde2c.jpg)

**Comment by Tanuj22** [comment]
@MohanChhabaria Try to add `Career Counselling Committee Members` and check if doesn't lead to an overflow. If it doesn't open a PR
