### ISSUE TITLE
Sanatize form data and add captcha

### ISSUE THREAD

**Issue by Tanuj22** [anshulahuja98/spc_portal#81]
**Describe the bug**
We need to sanitize all form data and set up add captcha to form.

**Comment by DarshitJain04** [comment]
@Tanuj22  I'll try to fix this issue. In which all forms do I need to add captcha?

**Comment by Tanuj22** [comment]
> @Tanuj22 I'll try to fix this issue. In which all forms do I need to add captcha?

The student and company registration. You also need to perform input validation like for all the field. Validation for some field are already done like username and email. Check [this](https://github.com/anshulahuja98/spc_portal/blob/52a7fcd4a1f5ecd1d0defa9fad6b27a456e722ae/src/accounts/forms.py#L86)

**Comment by Tanuj22** [comment]
You can generate it yourself the key yourself

**Comment by Tanuj22** [comment]
You can send separate PRs for captcha and form validation if you like

**Comment by DarshitJain04** [comment]
> > @Tanuj22 I'll try to fix this issue. In which all forms do I need to add captcha?
> 
> The student and company registration. You also need to perform input validation for all the field. Validation for some field are already done like username and email. Check [this](https://github.com/anshulahuja98/spc_portal/blob/52a7fcd4a1f5ecd1d0defa9fad6b27a456e722ae/src/accounts/forms.py#L86)

I'm not very clear with which all fields require validation. Could you please help?

**Comment by Tanuj22** [comment]
Like the contact should only contain a phone number and not a character. pin code should be a number. domain should be a link.

**Comment by DarshitJain04** [comment]
Oh okay!
